### ISSUE TITLE
Slow as fuck

### ISSUE THREAD

**Issue by Anduwu1** [Electro-Corp/CTGlobalConquest#1]

**Comment by Anduwu1** [comment]
I hear your mom is pretty quick and easy.

**Comment by Electro-Corp** [comment]
Damn
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYWFRgWFhYZGBgaHB4cHBocGhoaIRweHBgaGh4cHBocIS4lIR4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHhISHjQkJCE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NP/AABEIAMABBwMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAADBAIFAAEGB//EADsQAAIBAwIEBAQFAgQGAwAAAAECAAMRIQQSBTFBUQYiYXETgZHBMkKhsfBS0WJygvEUIyQ0suEHFjP/xAAYAQADAQEAAAAAAAAAAAAAAAAAAQIDBP/EACERAQEAAgMBAAIDAQAAAAAAAAABAhESITEDBDIiQVET/9oADAMBAAIRAxEAPwD0S0wSUy0ZbbBmTAJKINCbmTIgwTJoTIBuZMEi7gAk4EAofGOtRKDKW8xwAOt554n/AOfrmO+KKoqOXVr2O3n+sR1dkogD8TH9Jjnk6cMVA9Mg3E21MmTKwmi07ubKAe55AfOZet7qBKhAEw3JsL39BedBpuHItt93PbkB95eaVLfgWmg9syuFT/1jiF01Qi4SofZDIOWGDcH1uP3nq+gdgLF7/LnLB9Kjiz00cHuoP685P9q5PF957/rC6aqQ65JzPR+IeA6NQM9Amm39P4lP3E4DX8NqUKmyopVgcdiO4PaGi5DKWZ2QcxmTpavaR3EYoJavc/mXtKOobOe24w0Vyej8E8UqEKvi3KJ6XjtJKxe5IJ+856g/k5CL1FAzbE1mWoyuO7t11XVUalbfew7yz4VxVA92fy8hczz5NSOkHVfcecc+lK/OPWn4/QH5wZxHi3jdGs6gMRbrOabVbRbnK3UozHd0jmVpcZFnqaVzcMWEVqIBB0qjbME2gHrDOYvToIqbSb8plEFjIsSx9YanTYXPI9oyZUsCLfpMgkpkPn1+8yIPa6viqgL+a+YtqfF9NdthcG2fSeSs7G+f1mqjMRa5+s12z09sTxLp9oO9fa8quKeMUAPwmBInke02wZiUT3i2Ji9K4Z45NyKgBHpLOr42pWO3Bti/eeXUH2DMBqdVflJ5VXGPSdB4wYXLsD2EGnjY77sbKDkek42jW20t9vqIidRvzDlRcY9cTxppj+e0rOM+MaToyICb43dJ5iziWOkqgoVI9oXLoscZs3pqZNyMgZN5nEzZUPMEwvESESmoNicn1gOI0/IpJ64ziY10Y9UHR6X4ht0HM9pdqgUbVFhB8JobaY7nJ+0O+JWOsZtOUuV1C7ufcwIrMpwTDmRAjv0qp8Tun4q688zouFcY3kLgHtOSm0YggjmOszva5hY9W0bC1u/2g+LcIp6lNjr/AJW6qe4MqOAa34irnInVUxiVjN1ln08t4zw7/hwxqYKiyn+sHkZxLON1+/6T2Px/oBU0rEC7U/N8us8ZZL5HaGWOqrGy4rfRsLSVeji18GVmm1W0i8taeqDCIK2pptp5wY1ABGMiF19e5AESZJUiMqM9TzXgdXXOLTHqG1gIo24G5lSJ2LVchbRJb3zCVG6kzKRBjgtSU5jtOtyvEbH5SdBeYvChZF1JF/5iZFlSZENtMLEwb46yWw59zFytzLQNQfMOCIqtM39IxSpliABJqoIbEH+fOJuuZc0+HZHSRr6JQLAfOTKqypom/Sn/AAmVyWCy60FHZSdWubg/KUdQjaAPaOCwBlucSa1SGAkFa0J8K5BiyPFf8cpsUoMMXxN65A9Cw5qc+3Wa1ILJTN/wGHdNyOBzuPpeQv8AtY6cWVR2AkK56QyLYD0tf6SFRLxXJpjj2VaDA+n8MZdB3gT0k3JtMWAyV5oCSBi5HxO8L1bU3DL8xyvPTdBqt6A2t3E8nB9f5/eXPBNYFa3xKqN0Kjev+pbcpWOWrtj9MNx6DrE3o6nkykfUTxLRU/h1WDLdQxWx5c567pNU7AbirX/MAQCPY5BnnvimyV3RQPxXOO8e+VZScY57jehPxCUWykXAHKJpSe1uXznQcRqEIlu0rC3UzTGJtLppWAJuPYxRjtuTLB2Fr9pW6vVKRiPSaG+qGQBmKPVyBzi9UZveG2HB6ytJqbSNNYR6ZteR2G0AJQbdi9rQJqFGt6zTpyIHKTqAG2MwDK2pYEHp1mTaqGx1mQ6GhOpz1mzUAMxaV2OOp7942nD7gEx2pktCS5yBiWnDgL3tFqSbfL0jCDaMSMrtpjNLVYO1uchpKxODJancTYDEhbNQCUe3YzmUou/5be86nTDykEekiKYUco5dJs25SrSdSLj5y10tMEC/aM6sB8crQdFAptFldxWE7WtID4LehgEY47Ejp6wula6Ovpf6TWpYhFbmLDl0PrJ3pUxt8WrSNQ2g9PW3qD9QZCvXUYJt7TOunHxF39ZHePn3kfiA/mvJiovK4v6Wgtq1+Qmyh9Jsgf7TQYdoBsE/4Y9wrVuj4dFvg3Fx85WPqEHMW+0Y0Dozqo2Mb4DDB94Jy1Y7/Ts5ALKoPdDdW7ETg/Fx/wCpcdb/ALT0Dg5W2zZstyXp7j0nKcXp0ydTUdd7clv+U3tiXjZLtzZS3r/HOGxpAt0JtK34g6yx1K2pIPn7yscTXFlQzX5gYEpNaoDYlwy4lZqqbDpeXEUsaYAJvMSqLTdjkWij07SpolvRpl1JDfKAepfHbEWpOeQxJqhvkyTNU6eLtykKlunKNKrOoRRn2kDoXXDCIFG6ETI/q9IilQDe/wDaZDYXvEdCiVNwGHz8+sje9hawltV0y1EKfmpm4PpEBTF7XkW7aa0FT0oLQ9XQdRDIm3AhQ5GLwGiCaZh6Q1MHqMwhrG9oZKd4jiCfiGOsX4ktjcS0pou9cwmpoq3IRbPTntTT8txzlOga9zz7TqqmgYXPSV+u04Vd0LehJqhaGvjacXlvpkG3aeXrKDROd4FuuJcV3fAzlgD6SMvGvz1ui6kBSGvt6HtF6mnLevrf7x8rcWOfeLKvS9hJbSKuppUBywHputJ0yi8gD7Gb1/C9xFj/AHgl0g3DJFsWxbEC7lWNN78oPUagILn6RdE3kixAB9pOtpxa2SRyge+g11CsPMF9cxilSQgFWt7faVZ0l1IvfMtNHpAqi45QKdu34JxEbAtzuGBc8/W5lRx1gqVB+ZmH0MX4JpVcsG3WYgY/ab8R6daY2jCkjbck8ufOE9RlNbU/EzZEHpeVZF5a8YUeS3LbKwidGPjly9QtaCfJ5YhnEERGRV0HOAq0AY+1MwRXoYbSrfgEchGaVHy7j9I/RptY7UvF6lYoSCkez0suGPs87J0wYd+Ko67CtiZWVOLkpsC4iKuDkmTo9rmtRRbFlzMlC2sYnN/rMj40tx7BquHpTYOBYHB9jILwGkW5Z6yyraUuCG+X+8jwokg3Fip2nPO3Wc3K6dfGbIv4apnvIv4ZTox+s6C8wyeVHGOZ/wDrSLncTNPwUWsGxOkMBVqJyJhzyHDFzNfhJQE7jiGp6DeoKNa8dr6lQSt+eIHg6KSy35ZEvd0WpvQZ4BUIzU5xZ/CZb8T3E6GlUPMsNoxzkNTqlINmyJMyyPji5rU+F0pKX3/hyIpSTdTv1vzlrSqGq5BJKrzU94rRp/iUC/m5e8vvSZZLuBKuIu6c/wB47VpbcXB9oEyG8uwHcEc4qbAm2THKlMc4oWzYQNlJLX7xihUCm5Fx2g9s0RGehqwpsd6eU9U6e4klW6xZMw+zAt/PlApNLbwzT3VO4GfnIeMaZU01a+LnPS5jHh1dm9z0X7Ss4lqXrBGbmWx7CPGdsfpe1ZxgWZR2USvMZ17kub5tiK3m88c19aMzbMm4yaAmnkpEiAZ/x72xbHpK/U1WY3bJjNVcRcreA2UcQaR56VxaC+CY9pL7LsP50mRmnpmve0yPZae6xGm6pVKWtvFwe56x28Q4rgK45qf9xOGeu6zpYQdSoBzMW4hq9qblvkc5xes4tXdgFBMcxtK5SOn1niCminPmHTvOJ41x0ubqdt8Sr19N992BvzMEaJe3lv6zbHCY9sss7l0taGpshfcS0lpeJktkkE9RKuhTqE/DRGduwB/gnQ8N8MBLPqqwS2fhp5m9ieQlWJlS1PFnU/CGbi4PW8teD8Fr1POyMtuRfyj6HMYXilCl/wBvp1Df1uNzfrFtTxmvUuGfB6DAk8T2YK06TNd979QnIf6jE31BOEAQHnbmfcwCJiD1FQIjN2BlyQraCmtUu1MflEYnNcEclyx51Ln5CdGciZ/THjk6PjlyxRrNYSp12qVRg5hON6nagtzM586ZmF7ge8mReWWuostLxQAWY/OC1XFfNjkP1lYmkN+Y+si2lN7XH1lTGbZ3PLTpNNr1cAg2PUSyozk9LpGDpcHbfp9p2ui04LogvYnrJykni8crZ2uadF101TYpdiL4ybH06yko0iUQciDc3wR8p6FwNF2sRzvY+lpPiHCUqc1HvyI9VYco8Z0wzy3k8h1eXY9z94tadXx3wlWpXdL1U7AedR6jqPUTletiLHscW+U1xrK+tWmSV5Exk2BIuJK80wjAe2Q255YhjIk5gAnECIwwvmKuMwIVXPfEyQpE8vtMiN7Q5gtSqstm5Qhfncic3x7jOzyA39pyyWuzLKSN63XWoOoyUNvl0nIpxVy+LWHWWPh/UCs7o5/GMCUup4c6VHQX/FabzHTmytp7UareQLXY9pbaKmAoBX5f3MFw/RBFybseZ+0eVI9CMNQgEKAgPMKLfU84ArGdgtBWjlFAqYwOskiSSpc3hQsNjTFWUHifUbUKjrOg5TivE9Xc6J3YSsJvJOV1C4rCnVo9AFsfnznVaepe+b9vtOI8Qizr6S54VrsDJ5Zj/Jx72v8AFy1LKY41UUsq9RFOL6UkKw5Dt0gtc4L3JjWm4ioG0i4nPNzuOi6y3tU7Zp6RewUS3q6uhf8ADcdZOhqqdiQIbsTxnm06NO2xL2NxnnadPRf4LO7EH4a4t1YjE5jhTirXUHv/ALS98UVbOU7AE+9uUeOPKyFnlxlsdj4E1JeixY3JN/rky+1dZkBbG39pyvgBwE291B+fWdPxgkUXI7Qs0y9vZfTcZRjZrD17e8hxXw9p9SLsoDdHSwP9j85yyVLe3I+ol1QqrsFnNNl6g4Ye0JTyx/xyPGvB+ooXZf8Amp/Uosw90/tObvPZdBxBX8oqB2HMEW+lohxzwlR1ALqBTqf1KMH/ADDrNJkix5TebtH+McGraZrVE8vR1yp+fQ+8qXftKlSMTBtMVJJ1gACYN1jDgdYMj1gQdMZmSdIZ/naZAOo4p4ldztpqeZF7Ss0/CqrtuYHM7qjw6ne4UCT1dRaa8h7zCX/I6bjv2uSGhFBlcYII9Ja6plZ9wHb62lHW1LVq20m4B/QS6QZtLvSIiZJeU0Vkli2NJGAcWEM/KAVrn9I4K2gtJ2mhIk2jJqobCcXxuneuhv1nWamr9Zy3igFUDDB3WvNPn+0Z5+Kfjjh2upvbBtJcPYlbrm36e8hoqHlK7gd45f8AuLaJmRzYkML+2O/pOj6YcmWGXG7WVUFjmaKjkJd6dKeoWzAI9va/rBnw/X/Koa3YzkywuPVdWOcy7VB01zzF5DZbrLOpweuuDTa/tAtw+p+ZSgx5mxiTN0ZWTs74cHmvyt19ozxvWFwznNyFH15yrSoE8iPe/wCIjAt6RqutzSQHmw9Zv8/nx3lWP0z5axjvfCrbCM2wBOp47qB8E+ptOJ0ptb0jep17ONpOAbic+mwRMkz3A9MQYeRLgAwGxEYqQQbEdZd8K44U8j5X+rtOfV7wkB69BbZUUqQHUjIOQQZwXiHwIVJqaXI5mkT/AOB+xjnCuItTa17idQusvtZSLOPKega3Iwlqbi8PqPZiCCCMEHBHoRBjVgz07jfhylr0NRAKepXDW5MR0YetsGeWanTMjsjqVdCQwPQj7TSXaL0KagYfP+ZmGoCLRO8gz2laTs5SObzIrTq5t1mSuJbXlTjVUMSGI9oDV8aq1BZjjtK+rV8x/nKQd8YmUxa3J0Phx8u3YAfWdFT/ABTlPDLHZV/0zq9PkA9xM8vV4+CPIKISrBrCKrWoawgUFhJapuUCKl+scqaJugK1ax2g2Jm67MAbc+8qRTK/mJYZv37yuSbD6dj9ZVcdQFExfzfaWlCpfI5GV3GRdVH+K/6TT5TecR9L/Fz40O1w6G2cjvJHSXcnvkyyQQ24Acp39OXsuhU4Di47EY9pb8P4vsBDPkfwSkegjn8IB7gWMkaZVQQrM3YDp7ycsJlOzxtnjoNVxxreTJPUzl+I6l3JZ3b7R9GJF9pHyiero87cjzBixwxx8gyyyvpd0UUbtm9z/aH8JUC25zlQbLfp7Sv4kWYBEB2r8p1Xh7RGnQVWFicn5zP7XWLT5zdXtPlNzfDNaKTjcVK8jcXFusuOIcOQp8WiQU5lQb7fX29JxbdKpUzTTLTYEYQ08IHkaS4MmoiNvrH9JVvTdL2yHX0I7RGbiM++tZHFVDlgCwHccwR6yt/+S9IjJS1SAXYbGPcEXW/rzm6hxF+N1i2hqU2/Iyunpk3HtKxvacp04IgQTyTt1vBl5s59toMzJGkczJQGqIdxmiLdJcanhxBJXzL6RPUULdJHSu4svDWRV9hOh4Y90X0uP1lB4d5uP8MuOC1B51v+a/1mGc7b4eLGqZFJutMEU8VfQq2YJFEI5mrZ9o4mg6mJBMiOVcwKJAF9MLFh2P8AP3ifGGts+ceQ/wDMf2H7RHjFroOuZ0fH9ox+v6q4OZPcbSaILwxpYnda5ZC2nW5No0CR7dYHQpljGisVVJ00z4uBiANZW9/WMqIvqdIGGMHvELC4XcwA6m06OvUCIPQWA+05/hWmcVlDZXJv7S7Y7nJ6Jy/zTm/Iy8jX4z0jUoE4PNst9gI5oPi0s03IB5i9wflCBbxxFxOR0hUdbfDAg/URxGHU29YsUzyhnWOA5X2ALsJOPN7wSmRQYM2kRpmaM1fM3eAacXEruKv/ANPX/wAo/ePVnsDK3WAnTVj12/eGPqcvHEbTaQ2H2jNGmxNoPVptuJ0bc+g6R+cyZTZbzIw9F12xLqpGekoNRS3nH7S7PCSWs5+sKaSU+RvMZdN7Nqrg2gZGZjcXW0lw59tdl6MMD2Mfp6sswUDnKnWXTUI9sbrH2OJOXdPHqOgqnlJ9JBxe02WkKDcTQGD6zTgnpJv2tKBVpoCFKGRCHtAiNEeeofUD9JW8YYfEUdl/cy00ak7zm5c/pKziaXqHBuABOn4T+Tn+3hWmRHrgCKrpvU39pF1ZR6TsrCdGaCWue8KRB6b8IvCERVUaMUqVLRthE3XOBCFTnDK342/pX9TLDT0rKAcnmT3JlboKR2kWPmYDl0GZdfDzynH+Rf5Oj4/qxFjCjEGiekMqHtOdsjaSqDElsM06m0YbTlMSSUYtIXN+URpHnN9pg58pBvaSCnEKvTvGtFQDUnVsAr95V1bs9rdZc6NFN0e+0ixlBrRcH0173F/3loPD+mf8gPyiGppUafIkH1jOh4kqjq14raJIMPDGmH5F+kyOLrqb4JPtNyOWSuOL/9k=

**Comment by Anduwu1** [comment]
YOUR MOM

**Comment by Electro-Corp** [comment]
:cri:On Nov 29, 2022 7:44 PM, Androo ***@***.***> wrote:
YOUR MOM
